name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      # The Windows runners have autocrlf enabled by default.
      - name: Disable git autocrlf
        run: git config --global core.autocrlf false
        if: matrix.os == 'windows-latest'
      - name: Checkout
        uses: actions/checkout@v5
      # https://github.com/actions/cache/blob/main/examples.md#rust---cargo
      # Depends on `Cargo.lock` --> Has to be after checkout.
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        run: |
          rustup toolchain install nightly --no-self-update --profile minimal --component rust-src,rustfmt,clippy
          rustup target add wasm32-unknown-unknown
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run tests
        run: cargo test --all-features --all-targets
      - name: Run clippy
        run: cargo clippy --all-features --all-targets -- --no-deps --deny warnings
