name: Release

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          # Linux
          - bin_target: naijaup
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - bin_target: naijaup
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          # macOS
          - bin_target: naijaup
            os: macos-latest
            target: x86_64-apple-darwin
          - bin_target: naijaup
            os: macos-latest
            target: aarch64-apple-darwin
          # Windows (x86_64 only)
          - bin_target: naijaup
            os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        run: |
          rustup toolchain install nightly --no-self-update --profile minimal --component rust-src
          rustup target add ${{ matrix.target }}

      - name: Install cross toolchain and sysroot for aarch64-unknown-linux-gnu
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Build release binary
        run: |
          cargo build --config .cargo/release.toml --release --target ${{ matrix.target }} --bin ${{ matrix.bin_target }}

      - name: Set asset and archive names
        id: assetinfo
        run: |
          VERSION=${GITHUB_REF_NAME}
          NAME=${{ matrix.bin_target }}
          TARGET=${{ matrix.target }}
          EXT=tar.xz
          if [ "${{ matrix.os }}" = "windows-latest" ]; then EXT=zip; fi
          ASSET_NAME="$NAME-$VERSION-$TARGET"
          echo "asset_name=$ASSET_NAME" >> $GITHUB_OUTPUT
          echo "ext=$EXT" >> $GITHUB_OUTPUT

      - name: Archive binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $BinPath = "target/${{ matrix.target }}/release/${{ matrix.bin_target }}.exe"
          Compress-Archive -Path $BinPath -DestinationPath "${{ steps.assetinfo.outputs.asset_name }}.zip"

      - name: Archive binary (Unix/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          BIN_PATH=target/${{ matrix.target }}/release/${{ matrix.bin_target }}
          tar -cJf ${{ steps.assetinfo.outputs.asset_name }}.tar.xz -C $(dirname "$BIN_PATH") $(basename "$BIN_PATH")

      - name: Generate checksum
        id: checksum
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            sha256sum ${{ steps.assetinfo.outputs.asset_name }}.zip > ${{ steps.assetinfo.outputs.asset_name }}.sha256
            echo "artifacts=${{ steps.assetinfo.outputs.asset_name }}.zip ${{ steps.assetinfo.outputs.asset_name }}.sha256" >> $GITHUB_OUTPUT
          else
            if command -v sha256sum >/dev/null 2>&1; then
              sha256sum ${{ steps.assetinfo.outputs.asset_name }}.tar.xz > ${{ steps.assetinfo.outputs.asset_name }}.sha256
            else
              shasum -a 256 ${{ steps.assetinfo.outputs.asset_name }}.tar.xz > ${{ steps.assetinfo.outputs.asset_name }}.sha256
            fi
            echo "artifacts=${{ steps.assetinfo.outputs.asset_name }}.tar.xz ${{ steps.assetinfo.outputs.asset_name }}.sha256" >> $GITHUB_OUTPUT
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.assetinfo.outputs.asset_name }}
          path: ${{ steps.assetinfo.outputs.asset_name }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
